CREATE TABLE IF NOT EXISTS USER
    (
        ID              LONG(18)        NOT NULL AUTO_INCREMENT,
        FIRST_NAME      VARCHAR2(256)   NOT NULL,
        LAST_NAME       VARCHAR2(256)   NOT NULL,
        UPDATED_DATE    TIMESTAMP(3)    NOT NULL,
        CREATED_DATE    TIMESTAMP(3)    NOT NULL,
        CONSTRAINT USER_PK PRIMARY KEY (ID),
        CONSTRAINT USER_UN_FN_LN UNIQUE (FIRST_NAME, LAST_NAME)
    );